apply plugin: 'java'

repositories {
    mavenCentral()
}

// Set the Java version compatibility
sourceCompatibility = '17'
targetCompatibility = '17'

dependencies {
    implementation fileTree(dir: 'dependencies', include: ['*.jar'])
    implementation 'com.google.guava:guava:26.0-jre'
    implementation 'com.beust:jcommander:1.78'
    implementation 'com.github.spotbugs:spotbugs-annotations:3.1.8'
    implementation 'org.javatuples:javatuples:1.2'
    testImplementation 'junit:junit:4.12'
    testImplementation 'org.assertj:assertj-core:3.11.0'
    testImplementation group: 'org.hamcrest', name: 'hamcrest-library', version: '2.2'
}

// The lines below deal with exporting a running jar
jar {
    manifest {
        attributes 'Main-Class': 'br.ufpe.cin.app.JFSTMerge'
    }
}

task fatJar(type: Jar) {
    manifest.from jar.manifest
    classifier = 'all'

    // Set the duplicates strategy
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    } {
        exclude "META-INF/*.SF"
        exclude "META-INF/*.DSA"
        exclude "META-INF/*.RSA"
    }
    with jar
}

artifacts {
    archives fatJar
}

// Disabling asserts.
tasks.withType(Test) {
    enableAssertions = false
}
